# Generated by Django 3.2.4 on 2021-06-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='active',
            new_name='css',
        ),
    ]
