# Generated by Django 3.2.4 on 2021-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_rename_active_slider_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='slider',
            name='css',
            field=models.CharField(blank=True, choices=[('active', 'active')], max_length=70),
        ),
        migrations.AlterField(
            model_name='slider',
            name='headline',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=70),
        ),
    ]
