# Generated by Django 3.2.4 on 2021-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sliderId',
            field=models.CharField(choices=[('slider1', 'slider1'), ('slider2', 'slider2'), ('slider3', 'slider3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='css',
            field=models.CharField(choices=[('active', 'active')], max_length=70, null=True),
        ),
    ]
