# Generated by Django 3.2.4 on 2021-06-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_auto_20210616_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='css',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='subtitle',
        ),
    ]
