# Generated by Django 3.2.4 on 2021-06-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20210616_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='sliderId',
            new_name='headline',
        ),
    ]
