# Generated by Django 3.2.4 on 2021-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='slug',
        ),
    ]
