# Generated by Django 3.2.4 on 2021-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_auto_20210618_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(max_length=400),
        ),
    ]
