# Generated by Django 3.2.4 on 2021-06-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_auto_20210618_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Development',
        ),
    ]
