# Generated by Django 3.2.4 on 2021-06-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_rename_order_development'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Development',
            new_name='Order',
        ),
    ]
