# Generated by Django 3.2.4 on 2021-07-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_order_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
