# Generated by Django 3.2.4 on 2021-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='headline',
        ),
        migrations.AddField(
            model_name='plan',
            name='discountpercent',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='originalprice',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
