# Generated by Django 3.2.4 on 2021-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0022_slider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='headline',
            field=models.CharField(choices=[('slider1', 'slider1'), ('slider2', 'slider2'), ('slider3', 'slider3')], max_length=50, null=True),
        ),
    ]
