# Generated by Django 3.2.4 on 2021-06-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='auth_token',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
