# Generated by Django 3.2.4 on 2021-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210630_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='forget_password_token',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
