# Generated by Django 3.2.4 on 2021-06-21 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('writter', models.CharField(max_length=255)),
                ('writter_social', models.CharField(max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='media/blog/%Y/%m')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
